// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Xlh84uOelFXcdKJnT8WZA2HXBAAD_A4',
    appId: '1:297527898900:web:8a4dcb38ba8913b21a8801',
    messagingSenderId: '297527898900',
    projectId: 'zapchat-25640',
    authDomain: 'zapchat-25640.firebaseapp.com',
    storageBucket: 'zapchat-25640.firebasestorage.app',
    measurementId: 'G-JR7QYBWX9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdf9kmrgBurGSznZsbq6aUCBQUXYe17A',
    appId: '1:297527898900:android:75191a04b92de0ba1a8801',
    messagingSenderId: '297527898900',
    projectId: 'zapchat-25640',
    storageBucket: 'zapchat-25640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU9OIStRI6ZXa6KtsJIDd-6E76OmQAZsw',
    appId: '1:297527898900:ios:a01af16b45a1072a1a8801',
    messagingSenderId: '297527898900',
    projectId: 'zapchat-25640',
    storageBucket: 'zapchat-25640.firebasestorage.app',
    iosClientId: '297527898900-i0q9ccgb8vor9ih8tiunf4sbm4m7pjqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.zapchat',
  );
}
